title: <p align="center"> Naresh Kuppili </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nareshk90/">LinkedIn</a> |
  <a href="https://github.com/NareshKuppili">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
